project:
  type: website
  output-dir: docs

website:
  title: "Text Analysis Workshop"
  navbar:
    left:
      - text: "Home"
        href: Text-Analysis-Workshop/index.qmd
      - text: "Seminars"
        menu:
          - text: "Seminar 1"
            href: Text-Analysis-Workshop/Seminar/Seminar1.qmd
          - text: "Seminar 2"
            href: Text-Analysis-Workshop/Seminar/Seminar2.qmd
          - text: "Seminar 3"
            href: Text-Analysis-Workshop/Seminar/Seminar3.qmd
          - text: "Seminar 4"
            href: Text-Analysis-Workshop/Seminar/Seminar4.qmd
          - text: "Seminar 5"
            href: Text-Analysis-Workshop/Seminar/Seminar5.qmd
          - text: "Seminar 6"
            href: Text-Analysis-Workshop/Seminar/Seminar6.qmd
          - text: "Seminar 7"
            href: Text-Analysis-Workshop/Seminar/Seminar7.qmd
          - text: "简单R入门"
            href: 简单R入门.qmd
          - text: "Text-Analysis-Workshop/Tidyverse包介绍"
            href: Text-Analysis-Workshop/Tidyverse包介绍.qmd
          - text: "代码帮助"
            href: Text-Analysis-Workshop/代码帮助.qmd
format:
  html:
    theme: cosmo
    toc: true
